/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'fundInfo': RouteRecordInfo<'fundInfo', '/funds/fundInfo', Record<never, never>, Record<never, never>>,
    'subscribe': RouteRecordInfo<'subscribe', '/funds/subscribe', Record<never, never>, Record<never, never>>,
    'invest': RouteRecordInfo<'invest', '/invest', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'forget': RouteRecordInfo<'forget', '/login/forget', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/login/register', Record<never, never>, Record<never, never>>,
    'manager': RouteRecordInfo<'manager', '/manager', Record<never, never>, Record<never, never>>,
    'invite': RouteRecordInfo<'invite', '/manager/invite', Record<never, never>, Record<never, never>>,
    'inviteMember': RouteRecordInfo<'inviteMember', '/manager/inviteMember', Record<never, never>, Record<never, never>>,
    'news': RouteRecordInfo<'news', '/news', Record<never, never>, Record<never, never>>,
    'newsInfo': RouteRecordInfo<'newsInfo', '/news/info', Record<never, never>, Record<never, never>>,
    'payPassword': RouteRecordInfo<'payPassword', '/pay/password', Record<never, never>, Record<never, never>>,
    'recharge': RouteRecordInfo<'recharge', '/recharge', Record<never, never>, Record<never, never>>,
    'setting': RouteRecordInfo<'setting', '/setting', Record<never, never>, Record<never, never>>,
    'about': RouteRecordInfo<'about', '/setting/about', Record<never, never>, Record<never, never>>,
    'bindingEmail': RouteRecordInfo<'bindingEmail', '/setting/email', Record<never, never>, Record<never, never>>,
    'safety': RouteRecordInfo<'safety', '/setting/safety', Record<never, never>, Record<never, never>>,
    'user': RouteRecordInfo<'user', '/user', Record<never, never>, Record<never, never>>,
    'editInfo': RouteRecordInfo<'editInfo', '/user/editInfo', Record<never, never>, Record<never, never>>,
    'userRecord': RouteRecordInfo<'userRecord', '/user/record', Record<never, never>, Record<never, never>>,
    'userRecordInfo': RouteRecordInfo<'userRecordInfo', '/user/recordInfo', Record<never, never>, Record<never, never>>,
    'wallet': RouteRecordInfo<'wallet', '/wallet', Record<never, never>, Record<never, never>>,
    'withdraw': RouteRecordInfo<'withdraw', '/withdraw', Record<never, never>, Record<never, never>>,
  }
}
