/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'funds': RouteRecordInfo<'funds', '/funds', Record<never, never>, Record<never, never>>,
    'fundInfo': RouteRecordInfo<'fundInfo', '/funds/fundInfo', Record<never, never>, Record<never, never>>,
    'subscribe': RouteRecordInfo<'subscribe', '/funds/subscribe', Record<never, never>, Record<never, never>>,
    'invest': RouteRecordInfo<'invest', '/invest', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'forget': RouteRecordInfo<'forget', '/login/forget', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/login/register', Record<never, never>, Record<never, never>>,
    'login2': RouteRecordInfo<'login2', '/login2', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'news': RouteRecordInfo<'news', '/news', Record<never, never>, Record<never, never>>,
    'newsInfo': RouteRecordInfo<'newsInfo', '/news/info', Record<never, never>, Record<never, never>>,
    'payPassword': RouteRecordInfo<'payPassword', '/pay/password', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'recharge': RouteRecordInfo<'recharge', '/recharge', Record<never, never>, Record<never, never>>,
    'register2': RouteRecordInfo<'register2', '/register', Record<never, never>, Record<never, never>>,
    'setting': RouteRecordInfo<'setting', '/setting', Record<never, never>, Record<never, never>>,
    'bindingEmail': RouteRecordInfo<'bindingEmail', '/setting/email', Record<never, never>, Record<never, never>>,
    'safety': RouteRecordInfo<'safety', '/setting/safety', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
    'user': RouteRecordInfo<'user', '/user', Record<never, never>, Record<never, never>>,
    'userRecord': RouteRecordInfo<'userRecord', '/user/record', Record<never, never>, Record<never, never>>,
    'userRecordInfo': RouteRecordInfo<'userRecordInfo', '/user/recordInfo', Record<never, never>, Record<never, never>>,
    'wallet': RouteRecordInfo<'wallet', '/wallet', Record<never, never>, Record<never, never>>,
    'withdraw': RouteRecordInfo<'withdraw', '/withdraw', Record<never, never>, Record<never, never>>,
  }
}
